name: Advanced AFK
main: advancedafk.AdvancedAFK
version: 1.4
dev-url: http://http://dev.bukkit.org/server-mods/advanced-afk/
description: Advanced AFK System with AFKTerminator
commands:
  afk:
    description: Set yourself to AFK
permissions:
  advancedafk.*:
    description: All Permissions except "lagging"
  advancedafk.afk.self:
    description: Set self to AFK
    default: op
  advancedafk.afk.other:
    description: Set another player to AFK
    default: op
  advancedafk.lagging:
    description: Lagging players get 2 times more time to react
  advancedafk.exempt.afk:
    description: Makes the user exempt from being set to AFK
    default: op
  advancedafk.exempt.kick:
    description: Makes the user exempt from being kicked
    default: op
  advancedafk.reload:
    description: Reloads the plugin
    default: op